export const learningTopics = [
    {
        id: 'server-actions',
        title: 'Server Actions',
        description: 'Handle data mutations directly from forms with zero-cost abstraction. Learn form integration, validation, and server-side logic.',
        href: '/learning/serverActions',
        level: 'Intermediate',
        skills: ['Form handling', 'Backend integration', 'Type safety'],
    },
    {
        id: 'api-routes',
        title: 'API Routes & Middleware',
        description: 'Build RESTful APIs with Next.js route handlers. Master request/response handling, error handling, and middleware chains.',
        href: '/',
        level: 'Advanced',
        skills: ['HTTP methods', 'Request parsing', 'CORS handling'],
    },
    {
        id: 'database-prisma',
        title: 'Database with Prisma',
        description: 'Design schemas, run migrations, and write type-safe database queries. Learn ORM best practices and data modeling.',
        href: '/',
        level: 'Advanced',
        skills: ['Schema design', 'Migrations', 'CRUD operations'],
    },
    {
        id: 'authentication',
        title: 'Authentication & Authorization',
        description: 'Implement secure user sign-up, login, and session management. Master JWT, OAuth, and protected routes.',
        href: '/',
        level: 'Advanced',
        skills: ['JWT tokens', 'Session management', 'Protected routes'],
    },
    {
        id: 'caching-optimization',
        title: 'Caching & Performance',
        description: 'Optimize with Next.js caching strategies, incremental static regeneration, and database query optimization.',
        href: '/',
        level: 'Advanced',
        skills: ['ISR', 'Cache headers', 'Query optimization'],
    },
    {
        id: 'file-uploads',
        title: 'File Uploads & Storage',
        description: 'Handle file uploads, validate, and store in cloud services. Learn streaming, multipart forms, and object storage integration.',
        href: '/',
        level: 'Intermediate',
        skills: ['Multipart handling', 'S3 integration', 'File validation'],
    },
    {
        id: 'real-time',
        title: 'Real-time Features',
        description: 'Build real-time notifications with WebSockets, Server-Sent Events, and live data synchronization patterns.',
        href: '/',
        level: 'Advanced',
        skills: ['WebSockets', 'SSE', 'Live updates'],
    },
    {
        id: 'testing',
        title: 'Testing & Quality',
        description: 'Write unit tests, integration tests, and E2E tests. Master mocking, test coverage, and CI/CD integration.',
        href: '/',
        level: 'Advanced',
        skills: ['Jest', 'Testing Library', 'E2E testing'],
    },
    {
        id: 'deployment',
        title: 'Deployment & DevOps',
        description: 'Deploy to production with Vercel, Docker, and cloud platforms. Master environment variables and monitoring.',
        href: '/',
        level: 'Advanced',
        skills: ['Vercel deployment', 'Docker', 'Environment setup'],
    },
    {
        id: 'state-management',
        title: 'State Management',
        description: 'Master client-side state with React Context, Zustand, or Redux. Learn when to use server vs. client state.',
        href: '/',
        level: 'Intermediate',
        skills: ['Context API', 'Custom hooks', 'Store patterns'],
    },
    {
        id: 'seo-metadata',
        title: 'SEO & Metadata',
        description: 'Optimize for search engines with metadata, structured data, and sitemap generation in Next.js.',
        href: '/',
        level: 'Intermediate',
        skills: ['Meta tags', 'Schema.org', 'Sitemaps'],
    },
    {
        id: 'typescript',
        title: 'TypeScript Mastery',
        description: 'Write type-safe code with advanced TypeScript patterns, generics, and utility types for production apps.',
        href: '/',
        level: 'Advanced',
        skills: ['Generics', 'Utility types', 'Type guards'],
    },
];
