export const devModeTopics = [
    {
        id: 'server-actions',
        title: 'Server Actions',
        description: 'Form submission handling without fetch. Direct server function calls from components.',
        tags: ['forms', 'backend', 'next.js'],
        href: '/learning/serverActions',
    },
    {
        id: 'api-routes',
        title: 'API Routes & Middleware',
        description: 'Build REST endpoints with request/response handling, middleware chains, and error management.',
        tags: ['routing', 'http', 'backend'],
        href: '/',
    },
    {
        id: 'database-prisma',
        title: 'Database with Prisma',
        description: 'Schema design, migrations, CRUD operations. Type-safe database queries with ORM patterns.',
        tags: ['database', 'orm', 'schema'],
        href: '/',
    },
    {
        id: 'authentication',
        title: 'Authentication & Authorization',
        description: 'JWT tokens, session management, OAuth integration, protected routes and role-based access.',
        tags: ['auth', 'security', 'sessions'],
        href: '/',
    },
    {
        id: 'caching-optimization',
        title: 'Caching & Performance',
        description: 'ISR, cache headers, database optimization, lazy loading, code splitting strategies.',
        tags: ['performance', 'caching', 'optimization'],
        href: '/',
    },
    {
        id: 'file-uploads',
        title: 'File Uploads & Storage',
        description: 'Multipart form handling, file validation, S3 integration, streaming large files.',
        tags: ['files', 'storage', 'streams'],
        href: '/',
    },
    {
        id: 'real-time',
        title: 'Real-time Features',
        description: 'WebSockets, Server-Sent Events (SSE), live notifications, state synchronization.',
        tags: ['websockets', 'real-time', 'sockets'],
        href: '/',
    },
    {
        id: 'testing',
        title: 'Testing & QA',
        description: 'Jest setup, unit tests, integration tests, E2E with Playwright, coverage reports.',
        tags: ['testing', 'jest', 'playwright'],
        href: '/',
    },
    {
        id: 'deployment',
        title: 'Deployment & DevOps',
        description: 'Docker containerization, CI/CD pipelines, environment management, monitoring and logging.',
        tags: ['deployment', 'docker', 'devops'],
        href: '/',
    },
    {
        id: 'state-management',
        title: 'State Management',
        description: 'React Context, custom hooks, Zustand, Redux. Server vs client state patterns.',
        tags: ['state', 'hooks', 'context'],
        href: '/',
    },
    {
        id: 'seo-metadata',
        title: 'SEO & Metadata',
        description: 'Meta tags, structured data (schema.org), sitemap generation, dynamic metadata.',
        tags: ['seo', 'metadata', 'structured-data'],
        href: '/',
    },
    {
        id: 'typescript',
        title: 'TypeScript Deep Dive',
        description: 'Generics, utility types, type guards, advanced patterns, type inference optimization.',
        tags: ['typescript', 'types', 'advanced'],
        href: '/',
    },
];
